
== Preface

This is the reference manual of *MoonAL*, which is a 
http://www.lua.org[*Lua*] binding library for the 
https://openal.org[*OpenAL 3D Audio Library API*], targeted to the 
http://openal-soft.org[*OpenAL&nbsp;Soft*] implementation.
footnote:[
This manual is written in
http://www.methods.co.nz/asciidoc/[AsciiDoc], rendered with
http://asciidoctor.org/[AsciiDoctor] and a CSS from the
https://github.com/asciidoctor/asciidoctor-stylesheet-factory[AsciiDoctor Stylesheet Factory].]

It is assumed that the reader is familiar with both OpenAL and the Lua programming language.

For convenience of reference, this document contains external (deep) links to the 
http://www.lua.org/manual/5.3/manual.html[Lua Reference Manual].

The following OpenAL documentation will also be referenced in this manual: 

* https://www.openal.org/documentation/openal-1.1-specification.pdf[OpenAL 1.1 Specification (PDF)]
* https://openal.org/documentation/OpenAL_Programmers_Guide.pdf[OpenAL Programmer's Guide (PDF)]
* http://kcat.strangesoft.net/misc-downloads/Effects%20Extension%20Guide.pdf[Effects Extension Guide (PDF)]
* http://openal-soft.org/openal-extensions[OpenAL Soft extensions documents]
* https://github.com/openalext/openalext/wiki[OpenAL extensions Wiki]

=== Getting and installing

For installation intructions, refer to the README file in the 
https://github.com/stetre/moonal[*MoonAL official repository*]
on GitHub.

=== Module organization

The MoonAL module is loaded using Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-require[require]() and
returns a table containing the functions it provides 
(as usual with Lua modules). This manual assumes that such
table is named *al*, i.e. that it is loaded with:

[source,lua,indent=1]
----
al = require("moonal")
----

but nothing forbids the use of a different name.

=== Examples

////
@@ TODO
This manual contains a <<_code_snippets, code snippets section>> where short incomplete
examples show how to use MoonAL functions.
////

Complete examples can be found in the *examples/* directory of the release package.

=== License

MoonAL is released under the *MIT/X11 license* (same as
http://www.lua.org/license.html[Lua], and with the same only requirement to give proper
credits to the original author). 
The copyright notice is in the LICENSE file in the base directory
of the https://github.com/stetre/moonal[official repository] on GitHub.

[[see-also]]
=== See also

MoonAL is part of https://github.com/stetre/moonlibs[MoonLibs], a collection of 
Lua libraries for graphics and audio programming.

