/* The MIT License (MIT)
 *
 * Copyright (c) 2017 Stefano Trettel
 *
 * Software repository: MoonAL, https://github.com/stetre/moonal
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <float.h>
#include "internal.h"

#define ADD_INTEGER(x) do { lua_pushinteger(L, AL_##x); lua_setfield(L, -2, ""#x); } while(0)
#define ADD_NUMBER(x) do { lua_pushnumber(L, AL_##x); lua_setfield(L, -2, ""#x); } while(0)
#define ADD_BOOLEAN(x) do { lua_pushboolean(L, AL_##x); lua_setfield(L, -2, ""#x); } while(0)



void moonal_open_ranges(lua_State *L) //@@DOC, o rifare più smart, con funzione get_range()?
    {

    /* Lowpass filter */
    ADD_NUMBER(LOWPASS_MIN_GAIN);
    ADD_NUMBER(LOWPASS_MAX_GAIN);
    ADD_NUMBER(LOWPASS_DEFAULT_GAIN);

    ADD_NUMBER(LOWPASS_MIN_GAINHF);
    ADD_NUMBER(LOWPASS_MAX_GAINHF);
    ADD_NUMBER(LOWPASS_DEFAULT_GAINHF);

    /* Highpass filter */
    ADD_NUMBER(HIGHPASS_MIN_GAIN);
    ADD_NUMBER(HIGHPASS_MAX_GAIN);
    ADD_NUMBER(HIGHPASS_DEFAULT_GAIN);

    ADD_NUMBER(HIGHPASS_MIN_GAINLF);
    ADD_NUMBER(HIGHPASS_MAX_GAINLF);
    ADD_NUMBER(HIGHPASS_DEFAULT_GAINLF);

    /* Bandpass filter */
    ADD_NUMBER(BANDPASS_MIN_GAIN);
    ADD_NUMBER(BANDPASS_MAX_GAIN);
    ADD_NUMBER(BANDPASS_DEFAULT_GAIN);

    ADD_NUMBER(BANDPASS_MIN_GAINHF);
    ADD_NUMBER(BANDPASS_MAX_GAINHF);
    ADD_NUMBER(BANDPASS_DEFAULT_GAINHF);

    ADD_NUMBER(BANDPASS_MIN_GAINLF);
    ADD_NUMBER(BANDPASS_MAX_GAINLF);
    ADD_NUMBER(BANDPASS_DEFAULT_GAINLF);


    /* Effect parameter ranges and defaults. */

    /* Standard reverb effect */
    ADD_NUMBER(REVERB_MIN_DENSITY);
    ADD_NUMBER(REVERB_MAX_DENSITY);
    ADD_NUMBER(REVERB_DEFAULT_DENSITY);

    ADD_NUMBER(REVERB_MIN_DIFFUSION);
    ADD_NUMBER(REVERB_MAX_DIFFUSION);
    ADD_NUMBER(REVERB_DEFAULT_DIFFUSION);

    ADD_NUMBER(REVERB_MIN_GAIN);
    ADD_NUMBER(REVERB_MAX_GAIN);
    ADD_NUMBER(REVERB_DEFAULT_GAIN);

    ADD_NUMBER(REVERB_MIN_GAINHF);
    ADD_NUMBER(REVERB_MAX_GAINHF);
    ADD_NUMBER(REVERB_DEFAULT_GAINHF);

    ADD_NUMBER(REVERB_MIN_DECAY_TIME);
    ADD_NUMBER(REVERB_MAX_DECAY_TIME);
    ADD_NUMBER(REVERB_DEFAULT_DECAY_TIME);

    ADD_NUMBER(REVERB_MIN_DECAY_HFRATIO);
    ADD_NUMBER(REVERB_MAX_DECAY_HFRATIO);
    ADD_NUMBER(REVERB_DEFAULT_DECAY_HFRATIO);

    ADD_NUMBER(REVERB_MIN_REFLECTIONS_GAIN);
    ADD_NUMBER(REVERB_MAX_REFLECTIONS_GAIN);
    ADD_NUMBER(REVERB_DEFAULT_REFLECTIONS_GAIN);

    ADD_NUMBER(REVERB_MIN_REFLECTIONS_DELAY);
    ADD_NUMBER(REVERB_MAX_REFLECTIONS_DELAY);
    ADD_NUMBER(REVERB_DEFAULT_REFLECTIONS_DELAY);

    ADD_NUMBER(REVERB_MIN_LATE_REVERB_GAIN);
    ADD_NUMBER(REVERB_MAX_LATE_REVERB_GAIN);
    ADD_NUMBER(REVERB_DEFAULT_LATE_REVERB_GAIN);

    ADD_NUMBER(REVERB_MIN_LATE_REVERB_DELAY);
    ADD_NUMBER(REVERB_MAX_LATE_REVERB_DELAY);
    ADD_NUMBER(REVERB_DEFAULT_LATE_REVERB_DELAY);

    ADD_NUMBER(REVERB_MIN_AIR_ABSORPTION_GAINHF);
    ADD_NUMBER(REVERB_MAX_AIR_ABSORPTION_GAINHF);
    ADD_NUMBER(REVERB_DEFAULT_AIR_ABSORPTION_GAINHF);

    ADD_NUMBER(REVERB_MIN_ROOM_ROLLOFF_FACTOR);
    ADD_NUMBER(REVERB_MAX_ROOM_ROLLOFF_FACTOR);
    ADD_NUMBER(REVERB_DEFAULT_ROOM_ROLLOFF_FACTOR);

    ADD_BOOLEAN(REVERB_MIN_DECAY_HFLIMIT);
    ADD_BOOLEAN(REVERB_MAX_DECAY_HFLIMIT);
    ADD_BOOLEAN(REVERB_DEFAULT_DECAY_HFLIMIT);

    /* EAX reverb effect */
    ADD_NUMBER(EAXREVERB_MIN_DENSITY);
    ADD_NUMBER(EAXREVERB_MAX_DENSITY);
    ADD_NUMBER(EAXREVERB_DEFAULT_DENSITY);

    ADD_NUMBER(EAXREVERB_MIN_DIFFUSION);
    ADD_NUMBER(EAXREVERB_MAX_DIFFUSION);
    ADD_NUMBER(EAXREVERB_DEFAULT_DIFFUSION);

    ADD_NUMBER(EAXREVERB_MIN_GAIN);
    ADD_NUMBER(EAXREVERB_MAX_GAIN);
    ADD_NUMBER(EAXREVERB_DEFAULT_GAIN);

    ADD_NUMBER(EAXREVERB_MIN_GAINHF);
    ADD_NUMBER(EAXREVERB_MAX_GAINHF);
    ADD_NUMBER(EAXREVERB_DEFAULT_GAINHF);

    ADD_NUMBER(EAXREVERB_MIN_GAINLF);
    ADD_NUMBER(EAXREVERB_MAX_GAINLF);
    ADD_NUMBER(EAXREVERB_DEFAULT_GAINLF);

    ADD_NUMBER(EAXREVERB_MIN_DECAY_TIME);
    ADD_NUMBER(EAXREVERB_MAX_DECAY_TIME);
    ADD_NUMBER(EAXREVERB_DEFAULT_DECAY_TIME);

    ADD_NUMBER(EAXREVERB_MIN_DECAY_HFRATIO);
    ADD_NUMBER(EAXREVERB_MAX_DECAY_HFRATIO);
    ADD_NUMBER(EAXREVERB_DEFAULT_DECAY_HFRATIO);

    ADD_NUMBER(EAXREVERB_MIN_DECAY_LFRATIO);
    ADD_NUMBER(EAXREVERB_MAX_DECAY_LFRATIO);
    ADD_NUMBER(EAXREVERB_DEFAULT_DECAY_LFRATIO);

    ADD_NUMBER(EAXREVERB_MIN_REFLECTIONS_GAIN);
    ADD_NUMBER(EAXREVERB_MAX_REFLECTIONS_GAIN);
    ADD_NUMBER(EAXREVERB_DEFAULT_REFLECTIONS_GAIN);

    ADD_NUMBER(EAXREVERB_MIN_REFLECTIONS_DELAY);
    ADD_NUMBER(EAXREVERB_MAX_REFLECTIONS_DELAY);
    ADD_NUMBER(EAXREVERB_DEFAULT_REFLECTIONS_DELAY);

    ADD_NUMBER(EAXREVERB_DEFAULT_REFLECTIONS_PAN_XYZ);

    ADD_NUMBER(EAXREVERB_MIN_LATE_REVERB_GAIN);
    ADD_NUMBER(EAXREVERB_MAX_LATE_REVERB_GAIN);
    ADD_NUMBER(EAXREVERB_DEFAULT_LATE_REVERB_GAIN);

    ADD_NUMBER(EAXREVERB_MIN_LATE_REVERB_DELAY);
    ADD_NUMBER(EAXREVERB_MAX_LATE_REVERB_DELAY);
    ADD_NUMBER(EAXREVERB_DEFAULT_LATE_REVERB_DELAY);

    ADD_NUMBER(EAXREVERB_DEFAULT_LATE_REVERB_PAN_XYZ);

    ADD_NUMBER(EAXREVERB_MIN_ECHO_TIME);
    ADD_NUMBER(EAXREVERB_MAX_ECHO_TIME);
    ADD_NUMBER(EAXREVERB_DEFAULT_ECHO_TIME);

    ADD_NUMBER(EAXREVERB_MIN_ECHO_DEPTH);
    ADD_NUMBER(EAXREVERB_MAX_ECHO_DEPTH);
    ADD_NUMBER(EAXREVERB_DEFAULT_ECHO_DEPTH);

    ADD_NUMBER(EAXREVERB_MIN_MODULATION_TIME);
    ADD_NUMBER(EAXREVERB_MAX_MODULATION_TIME);
    ADD_NUMBER(EAXREVERB_DEFAULT_MODULATION_TIME);

    ADD_NUMBER(EAXREVERB_MIN_MODULATION_DEPTH);
    ADD_NUMBER(EAXREVERB_MAX_MODULATION_DEPTH);
    ADD_NUMBER(EAXREVERB_DEFAULT_MODULATION_DEPTH);

    ADD_NUMBER(EAXREVERB_MIN_AIR_ABSORPTION_GAINHF);
    ADD_NUMBER(EAXREVERB_MAX_AIR_ABSORPTION_GAINHF);
    ADD_NUMBER(EAXREVERB_DEFAULT_AIR_ABSORPTION_GAINHF);

    ADD_NUMBER(EAXREVERB_MIN_HFREFERENCE);
    ADD_NUMBER(EAXREVERB_MAX_HFREFERENCE);
    ADD_NUMBER(EAXREVERB_DEFAULT_HFREFERENCE);

    ADD_NUMBER(EAXREVERB_MIN_LFREFERENCE);
    ADD_NUMBER(EAXREVERB_MAX_LFREFERENCE);
    ADD_NUMBER(EAXREVERB_DEFAULT_LFREFERENCE);

    ADD_NUMBER(EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR);
    ADD_NUMBER(EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR);
    ADD_NUMBER(EAXREVERB_DEFAULT_ROOM_ROLLOFF_FACTOR);

    ADD_BOOLEAN(EAXREVERB_MIN_DECAY_HFLIMIT);
    ADD_BOOLEAN(EAXREVERB_MAX_DECAY_HFLIMIT);
    ADD_BOOLEAN(EAXREVERB_DEFAULT_DECAY_HFLIMIT);

    /* Chorus effect */
    ADD_INTEGER(CHORUS_WAVEFORM_SINUSOID);
    ADD_INTEGER(CHORUS_WAVEFORM_TRIANGLE);

    ADD_INTEGER(CHORUS_MIN_WAVEFORM);
    ADD_INTEGER(CHORUS_MAX_WAVEFORM);
    ADD_INTEGER(CHORUS_DEFAULT_WAVEFORM);

    ADD_INTEGER(CHORUS_MIN_PHASE);
    ADD_INTEGER(CHORUS_MAX_PHASE);
    ADD_INTEGER(CHORUS_DEFAULT_PHASE);

    ADD_NUMBER(CHORUS_MIN_RATE);
    ADD_NUMBER(CHORUS_MAX_RATE);
    ADD_NUMBER(CHORUS_DEFAULT_RATE);

    ADD_NUMBER(CHORUS_MIN_DEPTH);
    ADD_NUMBER(CHORUS_MAX_DEPTH);
    ADD_NUMBER(CHORUS_DEFAULT_DEPTH);

    ADD_NUMBER(CHORUS_MIN_FEEDBACK);
    ADD_NUMBER(CHORUS_MAX_FEEDBACK);
    ADD_NUMBER(CHORUS_DEFAULT_FEEDBACK);

    ADD_NUMBER(CHORUS_MIN_DELAY);
    ADD_NUMBER(CHORUS_MAX_DELAY);
    ADD_NUMBER(CHORUS_DEFAULT_DELAY);

    /* Distortion effect */
    ADD_NUMBER(DISTORTION_MIN_EDGE);
    ADD_NUMBER(DISTORTION_MAX_EDGE);
    ADD_NUMBER(DISTORTION_DEFAULT_EDGE);

    ADD_NUMBER(DISTORTION_MIN_GAIN);
    ADD_NUMBER(DISTORTION_MAX_GAIN);
    ADD_NUMBER(DISTORTION_DEFAULT_GAIN);

    ADD_NUMBER(DISTORTION_MIN_LOWPASS_CUTOFF);
    ADD_NUMBER(DISTORTION_MAX_LOWPASS_CUTOFF);
    ADD_NUMBER(DISTORTION_DEFAULT_LOWPASS_CUTOFF);

    ADD_NUMBER(DISTORTION_MIN_EQCENTER);
    ADD_NUMBER(DISTORTION_MAX_EQCENTER);
    ADD_NUMBER(DISTORTION_DEFAULT_EQCENTER);

    ADD_NUMBER(DISTORTION_MIN_EQBANDWIDTH);
    ADD_NUMBER(DISTORTION_MAX_EQBANDWIDTH);
    ADD_NUMBER(DISTORTION_DEFAULT_EQBANDWIDTH);

    /* Echo effect */
    ADD_NUMBER(ECHO_MIN_DELAY);
    ADD_NUMBER(ECHO_MAX_DELAY);
    ADD_NUMBER(ECHO_DEFAULT_DELAY);

    ADD_NUMBER(ECHO_MIN_LRDELAY);
    ADD_NUMBER(ECHO_MAX_LRDELAY);
    ADD_NUMBER(ECHO_DEFAULT_LRDELAY);

    ADD_NUMBER(ECHO_MIN_DAMPING);
    ADD_NUMBER(ECHO_MAX_DAMPING);
    ADD_NUMBER(ECHO_DEFAULT_DAMPING);

    ADD_NUMBER(ECHO_MIN_FEEDBACK);
    ADD_NUMBER(ECHO_MAX_FEEDBACK);
    ADD_NUMBER(ECHO_DEFAULT_FEEDBACK);

    ADD_NUMBER(ECHO_MIN_SPREAD);
    ADD_NUMBER(ECHO_MAX_SPREAD);
    ADD_NUMBER(ECHO_DEFAULT_SPREAD);

    /* Flanger effect */
    ADD_INTEGER(FLANGER_WAVEFORM_SINUSOID);
    ADD_INTEGER(FLANGER_WAVEFORM_TRIANGLE);

    ADD_INTEGER(FLANGER_MIN_WAVEFORM);
    ADD_INTEGER(FLANGER_MAX_WAVEFORM);
    ADD_INTEGER(FLANGER_DEFAULT_WAVEFORM);

    ADD_INTEGER(FLANGER_MIN_PHASE);
    ADD_INTEGER(FLANGER_MAX_PHASE);
    ADD_INTEGER(FLANGER_DEFAULT_PHASE);

    ADD_NUMBER(FLANGER_MIN_RATE);
    ADD_NUMBER(FLANGER_MAX_RATE);
    ADD_NUMBER(FLANGER_DEFAULT_RATE);

    ADD_NUMBER(FLANGER_MIN_DEPTH);
    ADD_NUMBER(FLANGER_MAX_DEPTH);
    ADD_NUMBER(FLANGER_DEFAULT_DEPTH);

    ADD_NUMBER(FLANGER_MIN_FEEDBACK);
    ADD_NUMBER(FLANGER_MAX_FEEDBACK);
    ADD_NUMBER(FLANGER_DEFAULT_FEEDBACK);

    ADD_NUMBER(FLANGER_MIN_DELAY);
    ADD_NUMBER(FLANGER_MAX_DELAY);
    ADD_NUMBER(FLANGER_DEFAULT_DELAY);

    /* Frequency shifter effect */
    ADD_NUMBER(FREQUENCY_SHIFTER_MIN_FREQUENCY);
    ADD_NUMBER(FREQUENCY_SHIFTER_MAX_FREQUENCY);
    ADD_NUMBER(FREQUENCY_SHIFTER_DEFAULT_FREQUENCY);

    ADD_INTEGER(FREQUENCY_SHIFTER_MIN_LEFT_DIRECTION);
    ADD_INTEGER(FREQUENCY_SHIFTER_MAX_LEFT_DIRECTION);
    ADD_INTEGER(FREQUENCY_SHIFTER_DEFAULT_LEFT_DIRECTION);

    ADD_INTEGER(FREQUENCY_SHIFTER_DIRECTION_DOWN);
    ADD_INTEGER(FREQUENCY_SHIFTER_DIRECTION_UP);
    ADD_INTEGER(FREQUENCY_SHIFTER_DIRECTION_OFF);

    ADD_INTEGER(FREQUENCY_SHIFTER_MIN_RIGHT_DIRECTION);
    ADD_INTEGER(FREQUENCY_SHIFTER_MAX_RIGHT_DIRECTION);
    ADD_INTEGER(FREQUENCY_SHIFTER_DEFAULT_RIGHT_DIRECTION);

    /* Vocal morpher effect */
    ADD_INTEGER(VOCAL_MORPHER_MIN_PHONEMEA);
    ADD_INTEGER(VOCAL_MORPHER_MAX_PHONEMEA);
    ADD_INTEGER(VOCAL_MORPHER_DEFAULT_PHONEMEA);

    ADD_INTEGER(VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING);
    ADD_INTEGER(VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING);
    ADD_INTEGER(VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING);

    ADD_INTEGER(VOCAL_MORPHER_MIN_PHONEMEB);
    ADD_INTEGER(VOCAL_MORPHER_MAX_PHONEMEB);
    ADD_INTEGER(VOCAL_MORPHER_DEFAULT_PHONEMEB);

    ADD_INTEGER(VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING);
    ADD_INTEGER(VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING);
    ADD_INTEGER(VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING);

    ADD_INTEGER(VOCAL_MORPHER_PHONEME_A);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_E);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_I);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_O);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_U);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_AA);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_AE);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_AH);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_AO);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_EH);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_ER);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_IH);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_IY);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_UH);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_UW);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_B);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_D);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_F);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_G);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_J);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_K);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_L);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_M);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_N);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_P);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_R);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_S);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_T);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_V);
    ADD_INTEGER(VOCAL_MORPHER_PHONEME_Z);

    ADD_INTEGER(VOCAL_MORPHER_WAVEFORM_SINUSOID);
    ADD_INTEGER(VOCAL_MORPHER_WAVEFORM_TRIANGLE);
    ADD_INTEGER(VOCAL_MORPHER_WAVEFORM_SAWTOOTH);

    ADD_INTEGER(VOCAL_MORPHER_MIN_WAVEFORM);
    ADD_INTEGER(VOCAL_MORPHER_MAX_WAVEFORM);
    ADD_INTEGER(VOCAL_MORPHER_DEFAULT_WAVEFORM);

    ADD_NUMBER(VOCAL_MORPHER_MIN_RATE);
    ADD_NUMBER(VOCAL_MORPHER_MAX_RATE);
    ADD_NUMBER(VOCAL_MORPHER_DEFAULT_RATE);

    /* Pitch shifter effect */
    ADD_INTEGER(PITCH_SHIFTER_MIN_COARSE_TUNE);
    ADD_INTEGER(PITCH_SHIFTER_MAX_COARSE_TUNE);
    ADD_INTEGER(PITCH_SHIFTER_DEFAULT_COARSE_TUNE);

    ADD_INTEGER(PITCH_SHIFTER_MIN_FINE_TUNE);
    ADD_INTEGER(PITCH_SHIFTER_MAX_FINE_TUNE);
    ADD_INTEGER(PITCH_SHIFTER_DEFAULT_FINE_TUNE);

    /* Ring modulator effect */
    ADD_NUMBER(RING_MODULATOR_MIN_FREQUENCY);
    ADD_NUMBER(RING_MODULATOR_MAX_FREQUENCY);
    ADD_NUMBER(RING_MODULATOR_DEFAULT_FREQUENCY);

    ADD_NUMBER(RING_MODULATOR_MIN_HIGHPASS_CUTOFF);
    ADD_NUMBER(RING_MODULATOR_MAX_HIGHPASS_CUTOFF);
    ADD_NUMBER(RING_MODULATOR_DEFAULT_HIGHPASS_CUTOFF);

    ADD_INTEGER(RING_MODULATOR_SINUSOID);
    ADD_INTEGER(RING_MODULATOR_SAWTOOTH);
    ADD_INTEGER(RING_MODULATOR_SQUARE);

    ADD_INTEGER(RING_MODULATOR_MIN_WAVEFORM);
    ADD_INTEGER(RING_MODULATOR_MAX_WAVEFORM);
    ADD_INTEGER(RING_MODULATOR_DEFAULT_WAVEFORM);

    /* Autowah effect */
    ADD_NUMBER(AUTOWAH_MIN_ATTACK_TIME);
    ADD_NUMBER(AUTOWAH_MAX_ATTACK_TIME);
    ADD_NUMBER(AUTOWAH_DEFAULT_ATTACK_TIME);

    ADD_NUMBER(AUTOWAH_MIN_RELEASE_TIME);
    ADD_NUMBER(AUTOWAH_MAX_RELEASE_TIME);
    ADD_NUMBER(AUTOWAH_DEFAULT_RELEASE_TIME);

    ADD_NUMBER(AUTOWAH_MIN_RESONANCE);
    ADD_NUMBER(AUTOWAH_MAX_RESONANCE);
    ADD_NUMBER(AUTOWAH_DEFAULT_RESONANCE);

    ADD_NUMBER(AUTOWAH_MIN_PEAK_GAIN);
    ADD_NUMBER(AUTOWAH_MAX_PEAK_GAIN);
    ADD_NUMBER(AUTOWAH_DEFAULT_PEAK_GAIN);

    /* Compressor effect */
    ADD_INTEGER(COMPRESSOR_MIN_ONOFF);
    ADD_INTEGER(COMPRESSOR_MAX_ONOFF);
    ADD_INTEGER(COMPRESSOR_DEFAULT_ONOFF);

    /* Equalizer effect */
    ADD_NUMBER(EQUALIZER_MIN_LOW_GAIN);
    ADD_NUMBER(EQUALIZER_MAX_LOW_GAIN);
    ADD_NUMBER(EQUALIZER_DEFAULT_LOW_GAIN);

    ADD_NUMBER(EQUALIZER_MIN_LOW_CUTOFF);
    ADD_NUMBER(EQUALIZER_MAX_LOW_CUTOFF);
    ADD_NUMBER(EQUALIZER_DEFAULT_LOW_CUTOFF);

    ADD_NUMBER(EQUALIZER_MIN_MID1_GAIN);
    ADD_NUMBER(EQUALIZER_MAX_MID1_GAIN);
    ADD_NUMBER(EQUALIZER_DEFAULT_MID1_GAIN);

    ADD_NUMBER(EQUALIZER_MIN_MID1_CENTER);
    ADD_NUMBER(EQUALIZER_MAX_MID1_CENTER);
    ADD_NUMBER(EQUALIZER_DEFAULT_MID1_CENTER);

    ADD_NUMBER(EQUALIZER_MIN_MID1_WIDTH);
    ADD_NUMBER(EQUALIZER_MAX_MID1_WIDTH);
    ADD_NUMBER(EQUALIZER_DEFAULT_MID1_WIDTH);

    ADD_NUMBER(EQUALIZER_MIN_MID2_GAIN);
    ADD_NUMBER(EQUALIZER_MAX_MID2_GAIN);
    ADD_NUMBER(EQUALIZER_DEFAULT_MID2_GAIN);

    ADD_NUMBER(EQUALIZER_MIN_MID2_CENTER);
    ADD_NUMBER(EQUALIZER_MAX_MID2_CENTER);
    ADD_NUMBER(EQUALIZER_DEFAULT_MID2_CENTER);

    ADD_NUMBER(EQUALIZER_MIN_MID2_WIDTH);
    ADD_NUMBER(EQUALIZER_MAX_MID2_WIDTH);
    ADD_NUMBER(EQUALIZER_DEFAULT_MID2_WIDTH);

    ADD_NUMBER(EQUALIZER_MIN_HIGH_GAIN);
    ADD_NUMBER(EQUALIZER_MAX_HIGH_GAIN);
    ADD_NUMBER(EQUALIZER_DEFAULT_HIGH_GAIN);

    ADD_NUMBER(EQUALIZER_MIN_HIGH_CUTOFF);
    ADD_NUMBER(EQUALIZER_MAX_HIGH_CUTOFF);
    ADD_NUMBER(EQUALIZER_DEFAULT_HIGH_CUTOFF);


    /* Source parameter value ranges and defaults. */
    ADD_NUMBER(MIN_AIR_ABSORPTION_FACTOR);
    ADD_NUMBER(MAX_AIR_ABSORPTION_FACTOR);
    ADD_NUMBER(DEFAULT_AIR_ABSORPTION_FACTOR);

    ADD_NUMBER(MIN_ROOM_ROLLOFF_FACTOR);
    ADD_NUMBER(MAX_ROOM_ROLLOFF_FACTOR);
    ADD_NUMBER(DEFAULT_ROOM_ROLLOFF_FACTOR);

    ADD_NUMBER(MIN_CONE_OUTER_GAINHF);
    ADD_NUMBER(MAX_CONE_OUTER_GAINHF);
    ADD_NUMBER(DEFAULT_CONE_OUTER_GAINHF);

    ADD_BOOLEAN(MIN_DIRECT_FILTER_GAINHF_AUTO);
    ADD_BOOLEAN(MAX_DIRECT_FILTER_GAINHF_AUTO);
    ADD_BOOLEAN(DEFAULT_DIRECT_FILTER_GAINHF_AUTO);

    ADD_BOOLEAN(MIN_AUXILIARY_SEND_FILTER_GAIN_AUTO);
    ADD_BOOLEAN(MAX_AUXILIARY_SEND_FILTER_GAIN_AUTO);
    ADD_BOOLEAN(DEFAULT_AUXILIARY_SEND_FILTER_GAIN_AUTO);

    ADD_BOOLEAN(MIN_AUXILIARY_SEND_FILTER_GAINHF_AUTO);
    ADD_BOOLEAN(MAX_AUXILIARY_SEND_FILTER_GAINHF_AUTO);
    ADD_BOOLEAN(DEFAULT_AUXILIARY_SEND_FILTER_GAINHF_AUTO);

    /* Listener parameter value ranges and defaults. */
    ADD_NUMBER(MIN_METERS_PER_UNIT);
    ADD_NUMBER(MAX_METERS_PER_UNIT);
    ADD_NUMBER(DEFAULT_METERS_PER_UNIT);
    }
